### ISSUE TITLE
 &amp;  and &amp;#8212

### ISSUE THREAD

**Issue by GrayLocus** [sdarlington/WSLHTMLEntities#1]
I've found the string "&amp;" end with #8212 is correctly translate to "&#8212", that what i want. But string like "&amp;" end with a space character is also translate to '&', may be this is a issue or not.

**Comment by GrayLocus** [comment]
I've found the string - &amp; end with #8212 is correctly translate to "&#8212", that what i want. But string like &amp; end with a space character is also translate to '&', may be this is a issue or not.

**Comment by GrayLocus** [comment]
String "&" is equal to &amp ;

**Comment by sdarlington** [comment]
The idea is that things that don't match The Pattern are left alone (see `WSLHTMLEntities.lm` for the list of patterns that are recognised). Patterns beginning with an ampersand and ending in a space are not recognised (they need to end in a semi-colon), so no translation is performed.

Examples:

&amp; -> &  (pattern matched, so converted)
& -> &   (no pattern, no conversion)
&amp;#8212 -> &#8212    (pattern matched, so converted)
&#8212 -> &#8212    (no pattern, no conversion)
&#8212; -> &#8212; (pattern matched, converted)

**Comment by GrayLocus** [comment]
Thanks for your answer.
